<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3JrXdCv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3JrXdCv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3JrXdCv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3JrXdCv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3JrXdCv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3JrXdCv',
    'container.build_id' => '84c2924a',
    'container.build_time' => 1576352623,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3JrXdCv');
